version: '3'

services:
  database:
    image: postgres:latest
    restart: always
    ports:
      - 9432:5432
    environment:
      - POSTGRES_DB=z-games
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dbpass123